apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - aws-registry-credential-cron.yaml  
replicas:
- name: chat
  count: 1
- name: editor
  count: 1
- name: match
  count: 1
- name: question
  count: 1
- name: user
  count: 1
- name: video-chat
  count: 1
