apiVersion: v1
kind: Service
metadata:
  name: question
  namespace: peerprep
spec:
  selector:
    app: question
  type: NodePort
  ports:
   -  protocol: TCP
      port: 3002
      targetPort: 3002
