apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# generatorOptions modify behavior of all ConfigMap and Secret generators
generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true

secretGenerator:
  - name: user-env
    namespace: peerprep
    envs:
      - .env

resources:
  - deployment.yaml
  - service.yaml
