apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: editor
  labels:
    app: editor
  namespace: peerprep
spec:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: editor
