apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: user-env
          ports:
            - containerPort: 3001
              protocol: TCP
      imagePullSecrets:
        - name: regcred
