apiVersion: apps/v1
kind: Deployment
metadata:
  name: question
  labels:
    app: question
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
        - name: question
          image: question
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: question-env
          ports:
            - containerPort: 3002
              protocol: TCP
      imagePullSecrets:
        - name: regcred
