apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: chat
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: chat-env
          ports:
            - containerPort: 3005
              protocol: TCP
      imagePullSecrets:
        - name: regcred
