apiVersion: v1
kind: Service
metadata:
  name: video-chat
  namespace: peerprep
spec:
  selector:
    app: video-chat
  type: NodePort
  ports:
   -  protocol: TCP
      port: 3007
      targetPort: 3007
