---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: editor
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/editor
  interval: 1m0s
