apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: peerprep
  name: peerprep
---
apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: peerprep
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: chat
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: editor
  namespace: peerprep
spec:
  ports:
  - port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: editor
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: match
  namespace: peerprep
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: match
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: question
  namespace: peerprep
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: question
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: peerprep
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: user
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chat
  name: chat
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: chat-env
        image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/chat-ms:master-7ab8b7c-1635957331
        imagePullPolicy: Always
        name: chat
        ports:
        - containerPort: 3005
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: editor
  name: editor
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: editor-env
        image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/editor-ms:master-7ab8b7c-1635957316
        imagePullPolicy: Always
        name: editor
        ports:
        - containerPort: 3004
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: match
  name: match
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: match-env
        image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/match-ms:master-7ab8b7c-1635957305
        imagePullPolicy: Always
        name: match
        ports:
        - containerPort: 3003
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: question
  name: question
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: question-env
        image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/question-ms:master-7ab8b7c-1635957304
        imagePullPolicy: Always
        name: question
        ports:
        - containerPort: 3002
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: user-env
        image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/user-ms:master-7ab8b7c-1635957320
        imagePullPolicy: Always
        name: user
        ports:
        - containerPort: 3001
          protocol: TCP
      imagePullSecrets:
      - name: regcred
