loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: standard
    size: 1Gi

promtail:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 8.1.6

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: true
  server:
    persistentVolume:
      enabled: true