---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: question
  namespace: flux-system
spec:
  image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/question-ms
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: question
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: question
  policy:
    semver:
      range: '>=1.0.0'
