---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: user
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: 694217600744.dkr.ecr.ap-southeast-1.amazonaws.com/user-ms
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: user
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: user
  policy:
    semver:
      range: '>=1.0.0'
