apiVersion: apps/v1
kind: Deployment
metadata:
  name: editor
  labels:
    app: editor
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editor
  template:
    metadata:
      labels:
        app: editor
    spec:
      containers:
        - name: editor
          image: editor
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: editor-env
          ports:
            - containerPort: 3004
              protocol: TCP
      imagePullSecrets:
        - name: regcred
