name: Build and Deploy Admin Frontend
on:
  push:
    branches:
      - master
    paths:
      - 'admin-frontend/**'
defaults:
  run:
    working-directory: ./admin-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: yarn

        - name: Build
          run: yarn generate

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: dist
            bucket: ${{ secrets.S3_ADMIN_STAGING_BUCKET }}
            bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
            dist-id: ${{ secrets.ADMIN_STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /*
            delete-removed: true
            no-cache: true
            private: true
